import React from "react";
import { SITE_INFO, SOURCE_CODE_GITHUB_URL } from "@/config/site";
import { cn } from "@/lib/utils";
import { RssIcon } from "lucide-react";
import { Icons } from "./icons";

const Footer = () => {
  return (
    <>
      <footer className="relative container-wrapper max-w-screen! overflow-x-hidden px-2">
        <div className="bg-[#f5f3f4] dark:bg-[#121316] border-t px-0 mx-auto border-x border-edge pt-4 container md:fixed:max-w-6xl">
          <p className="mb-4 px-4 text-center font-mono text-sm text-balance text-muted-foreground">
            Built by{" "}
            <a
              className="link"
              href="https://github.com/admin12121"
              target="_blank"
              rel="noopener"
            >
              admin12121
            </a>
            . The source code is available on{" "}
            <a
              className="link"
              href={SOURCE_CODE_GITHUB_URL}
              target="_blank"
              rel="noopener"
            >
              GitHub
            </a>
            .
          </p>
          <div
            className={cn(
              "border-t flex w-full before:z-1 after:z-1",
              "bg-[repeating-linear-gradient(315deg,var(--pattern-foreground)_0,var(--pattern-foreground)_1px,transparent_0,transparent_50%)] bg-size-[10px_10px] [--pattern-foreground:var(--color-edge)]/56",
            )}
          >
            <div className="mx-auto flex items-center justify-center gap-3 border-x border-edge bg-background px-4">
              <a
                className="flex font-mono text-xs font-medium text-muted-foreground"
                href={`${SITE_INFO.url}/llms.txt`}
                target="_blank"
                rel="noopener noreferrer"
              >
                llms.txt
              </a>

              <Separator />

              <a
                className="flex items-center text-muted-foreground transition-[color] hover:text-foreground"
                href="https://x.com/dmin12121?utm_source=admin12121.com"
                target="_blank"
                rel="noopener"
              >
                <Icons.x className="size-4" />
                <span className="sr-only">X</span>
              </a>

              <Separator />

              <a
                className="flex items-center text-muted-foreground transition-[color] hover:text-foreground"
                href="https://github.com/admin12121?utm_source=admin12121.com"
                target="_blank"
                rel="noopener"
              >
                <Icons.github className="size-4" />
                <span className="sr-only">GitHub</span>
              </a>

              <Separator />

              <a
                className="flex items-center text-muted-foreground transition-[color] hover:text-foreground"
                href="https://www.linkedin.com/in/vickytajpuriya?utm_source=admin12121.com"
                target="_blank"
                rel="noopener"
              >
                <Icons.linkedin className="size-4" />
                <span className="sr-only">LinkedIn</span>
              </a>

              <Separator />

              <a
                className="flex items-center text-muted-foreground transition-colors hover:text-foreground"
                href={`${SITE_INFO.url}/rss`}
                target="_blank"
                rel="noopener noreferrer"
              >
                <RssIcon className="size-4" />
                <span className="sr-only">RSS</span>
              </a>
            </div>
          </div>
        </div>
      </footer>
      <div className="px-0 mx-auto container md:fixed:max-w-6xl overflow-hidden border-x border-edge">
        <div className="relative py-6 -mb-16 col-span-full flex justify-center border-white/10 h-[242px]">
          <svg className="pointer-events-none absolute inset-0 [z-index:-1] size-full select-none text-slate-950/[0.06] dark:text-zinc-400/[0.08]">
            <defs>
              <pattern
                id="_S_e_"
                width="4"
                height="4"
                patternUnits="userSpaceOnUse"
                patternTransform="rotate(45)"
              >
                <line
                  x1="0"
                  y1="0"
                  x2="0"
                  y2="4"
                  stroke="currentColor"
                  strokeWidth="1.5"
                ></line>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#_S_e_)"></rect>
          </svg>
          <svg
            aria-hidden="true"
            className="pointer-events-none absolute inset-0 [z-index:-1] size-full stroke-slate-950/[0.08] dark:stroke-zinc-400/[0.12]"
          >
            <defs>
              <pattern
                id="_S_f_"
                width="16"
                height="1000"
                patternUnits="userSpaceOnUse"
                x="-1"
                y="-1"
              >
                <line x1="0" y1="0" x2="100%" y2="0" strokeOpacity="1"></line>
                <line
                  x1="0"
                  y1="10"
                  x2="100%"
                  y2="10"
                  strokeOpacity="0.99"
                ></line>
                <line
                  x1="0"
                  y1="20"
                  x2="100%"
                  y2="20"
                  strokeOpacity="0.98"
                ></line>
                <line
                  x1="0"
                  y1="30"
                  x2="100%"
                  y2="30"
                  strokeOpacity="0.97"
                ></line>
                <line
                  x1="0"
                  y1="40"
                  x2="100%"
                  y2="40"
                  strokeOpacity="0.96"
                ></line>
                <line
                  x1="0"
                  y1="50"
                  x2="100%"
                  y2="50"
                  strokeOpacity="0.95"
                ></line>
                <line
                  x1="0"
                  y1="60"
                  x2="100%"
                  y2="60"
                  strokeOpacity="0.94"
                ></line>
                <line
                  x1="0"
                  y1="70"
                  x2="100%"
                  y2="70"
                  strokeOpacity="0.93"
                ></line>
                <line
                  x1="0"
                  y1="80"
                  x2="100%"
                  y2="80"
                  strokeOpacity="0.92"
                ></line>
                <line
                  x1="0"
                  y1="90"
                  x2="100%"
                  y2="90"
                  strokeOpacity="0.91"
                ></line>
                <line
                  x1="0"
                  y1="100"
                  x2="100%"
                  y2="100"
                  strokeOpacity="0.9"
                ></line>
                <line
                  x1="0"
                  y1="110"
                  x2="100%"
                  y2="110"
                  strokeOpacity="0.89"
                ></line>
                <line
                  x1="0"
                  y1="120"
                  x2="100%"
                  y2="120"
                  strokeOpacity="0.88"
                ></line>
                <line
                  x1="0"
                  y1="130"
                  x2="100%"
                  y2="130"
                  strokeOpacity="0.87"
                ></line>
                <line
                  x1="0"
                  y1="140"
                  x2="100%"
                  y2="140"
                  strokeOpacity="0.86"
                ></line>
                <line
                  x1="0"
                  y1="150"
                  x2="100%"
                  y2="150"
                  strokeOpacity="0.85"
                ></line>
                <line
                  x1="0"
                  y1="160"
                  x2="100%"
                  y2="160"
                  strokeOpacity="0.84"
                ></line>
                <line
                  x1="0"
                  y1="170"
                  x2="100%"
                  y2="170"
                  strokeOpacity="0.83"
                ></line>
                <line
                  x1="0"
                  y1="180"
                  x2="100%"
                  y2="180"
                  strokeOpacity="0.82"
                ></line>
                <line
                  x1="0"
                  y1="190"
                  x2="100%"
                  y2="190"
                  strokeOpacity="0.81"
                ></line>
                <line
                  x1="0"
                  y1="200"
                  x2="100%"
                  y2="200"
                  strokeOpacity="0.8"
                ></line>
                <line
                  x1="0"
                  y1="210"
                  x2="100%"
                  y2="210"
                  strokeOpacity="0.79"
                ></line>
                <line
                  x1="0"
                  y1="220"
                  x2="100%"
                  y2="220"
                  strokeOpacity="0.78"
                ></line>
                <line
                  x1="0"
                  y1="230"
                  x2="100%"
                  y2="230"
                  strokeOpacity="0.77"
                ></line>
                <line
                  x1="0"
                  y1="240"
                  x2="100%"
                  y2="240"
                  strokeOpacity="0.76"
                ></line>
                <line
                  x1="0"
                  y1="250"
                  x2="100%"
                  y2="250"
                  strokeOpacity="0.75"
                ></line>
                <line
                  x1="0"
                  y1="260"
                  x2="100%"
                  y2="260"
                  strokeOpacity="0.74"
                ></line>
                <line
                  x1="0"
                  y1="270"
                  x2="100%"
                  y2="270"
                  strokeOpacity="0.73"
                ></line>
                <line
                  x1="0"
                  y1="280"
                  x2="100%"
                  y2="280"
                  strokeOpacity="0.72"
                ></line>
                <line
                  x1="0"
                  y1="290"
                  x2="100%"
                  y2="290"
                  strokeOpacity="0.71"
                ></line>
                <line
                  x1="0"
                  y1="300"
                  x2="100%"
                  y2="300"
                  strokeOpacity="0.7"
                ></line>
                <line
                  x1="0"
                  y1="310"
                  x2="100%"
                  y2="310"
                  strokeOpacity="0.69"
                ></line>
                <line
                  x1="0"
                  y1="320"
                  x2="100%"
                  y2="320"
                  strokeOpacity="0.68"
                ></line>
                <line
                  x1="0"
                  y1="330"
                  x2="100%"
                  y2="330"
                  strokeOpacity="0.67"
                ></line>
                <line
                  x1="0"
                  y1="340"
                  x2="100%"
                  y2="340"
                  strokeOpacity="0.66"
                ></line>
                <line
                  x1="0"
                  y1="350"
                  x2="100%"
                  y2="350"
                  strokeOpacity="0.65"
                ></line>
                <line
                  x1="0"
                  y1="360"
                  x2="100%"
                  y2="360"
                  strokeOpacity="0.64"
                ></line>
                <line
                  x1="0"
                  y1="370"
                  x2="100%"
                  y2="370"
                  strokeOpacity="0.63"
                ></line>
                <line
                  x1="0"
                  y1="380"
                  x2="100%"
                  y2="380"
                  strokeOpacity="0.62"
                ></line>
                <line
                  x1="0"
                  y1="390"
                  x2="100%"
                  y2="390"
                  strokeOpacity="0.61"
                ></line>
                <line
                  x1="0"
                  y1="400"
                  x2="100%"
                  y2="400"
                  strokeOpacity="0.6"
                ></line>
                <line
                  x1="0"
                  y1="410"
                  x2="100%"
                  y2="410"
                  strokeOpacity="0.59"
                ></line>
                <line
                  x1="0"
                  y1="420"
                  x2="100%"
                  y2="420"
                  strokeOpacity="0.58"
                ></line>
                <line
                  x1="0"
                  y1="430"
                  x2="100%"
                  y2="430"
                  strokeOpacity="0.57"
                ></line>
                <line
                  x1="0"
                  y1="440"
                  x2="100%"
                  y2="440"
                  strokeOpacity="0.56"
                ></line>
                <line
                  x1="0"
                  y1="450"
                  x2="100%"
                  y2="450"
                  strokeOpacity="0.55"
                ></line>
                <line
                  x1="0"
                  y1="460"
                  x2="100%"
                  y2="460"
                  strokeOpacity="0.54"
                ></line>
                <line
                  x1="0"
                  y1="470"
                  x2="100%"
                  y2="470"
                  strokeOpacity="0.53"
                ></line>
                <line
                  x1="0"
                  y1="480"
                  x2="100%"
                  y2="480"
                  strokeOpacity="0.52"
                ></line>
                <line
                  x1="0"
                  y1="490"
                  x2="100%"
                  y2="490"
                  strokeOpacity="0.51"
                ></line>
                <line
                  x1="0"
                  y1="500"
                  x2="100%"
                  y2="500"
                  strokeOpacity="0.5"
                ></line>
                <line
                  x1="0"
                  y1="510"
                  x2="100%"
                  y2="510"
                  strokeOpacity="0.49"
                ></line>
                <line
                  x1="0"
                  y1="520"
                  x2="100%"
                  y2="520"
                  strokeOpacity="0.48"
                ></line>
                <line
                  x1="0"
                  y1="530"
                  x2="100%"
                  y2="530"
                  strokeOpacity="0.47"
                ></line>
                <line
                  x1="0"
                  y1="540"
                  x2="100%"
                  y2="540"
                  strokeOpacity="0.46"
                ></line>
                <line
                  x1="0"
                  y1="550"
                  x2="100%"
                  y2="550"
                  strokeOpacity="0.45"
                ></line>
                <line
                  x1="0"
                  y1="560"
                  x2="100%"
                  y2="560"
                  strokeOpacity="0.44"
                ></line>
                <line
                  x1="0"
                  y1="570"
                  x2="100%"
                  y2="570"
                  strokeOpacity="0.43"
                ></line>
                <line
                  x1="0"
                  y1="580"
                  x2="100%"
                  y2="580"
                  strokeOpacity="0.42"
                ></line>
                <line
                  x1="0"
                  y1="590"
                  x2="100%"
                  y2="590"
                  strokeOpacity="0.41"
                ></line>
                <line
                  x1="0"
                  y1="600"
                  x2="100%"
                  y2="600"
                  strokeOpacity="0.4"
                ></line>
                <line
                  x1="0"
                  y1="610"
                  x2="100%"
                  y2="610"
                  strokeOpacity="0.39"
                ></line>
                <line
                  x1="0"
                  y1="620"
                  x2="100%"
                  y2="620"
                  strokeOpacity="0.38"
                ></line>
                <line
                  x1="0"
                  y1="630"
                  x2="100%"
                  y2="630"
                  strokeOpacity="0.37"
                ></line>
                <line
                  x1="0"
                  y1="640"
                  x2="100%"
                  y2="640"
                  strokeOpacity="0.36"
                ></line>
                <line
                  x1="0"
                  y1="650"
                  x2="100%"
                  y2="650"
                  strokeOpacity="0.35"
                ></line>
                <line
                  x1="0"
                  y1="660"
                  x2="100%"
                  y2="660"
                  strokeOpacity="0.34"
                ></line>
                <line
                  x1="0"
                  y1="670"
                  x2="100%"
                  y2="670"
                  strokeOpacity="0.33"
                ></line>
                <line
                  x1="0"
                  y1="680"
                  x2="100%"
                  y2="680"
                  strokeOpacity="0.32"
                ></line>
                <line
                  x1="0"
                  y1="690"
                  x2="100%"
                  y2="690"
                  strokeOpacity="0.31"
                ></line>
                <line
                  x1="0"
                  y1="700"
                  x2="100%"
                  y2="700"
                  strokeOpacity="0.3"
                ></line>
                <line
                  x1="0"
                  y1="710"
                  x2="100%"
                  y2="710"
                  strokeOpacity="0.29"
                ></line>
                <line
                  x1="0"
                  y1="720"
                  x2="100%"
                  y2="720"
                  strokeOpacity="0.28"
                ></line>
                <line
                  x1="0"
                  y1="730"
                  x2="100%"
                  y2="730"
                  strokeOpacity="0.27"
                ></line>
                <line
                  x1="0"
                  y1="740"
                  x2="100%"
                  y2="740"
                  strokeOpacity="0.26"
                ></line>
                <line
                  x1="0"
                  y1="750"
                  x2="100%"
                  y2="750"
                  strokeOpacity="0.25"
                ></line>
                <line
                  x1="0"
                  y1="760"
                  x2="100%"
                  y2="760"
                  strokeOpacity="0.24"
                ></line>
                <line
                  x1="0"
                  y1="770"
                  x2="100%"
                  y2="770"
                  strokeOpacity="0.23"
                ></line>
                <line
                  x1="0"
                  y1="780"
                  x2="100%"
                  y2="780"
                  strokeOpacity="0.22"
                ></line>
                <line
                  x1="0"
                  y1="790"
                  x2="100%"
                  y2="790"
                  strokeOpacity="0.21"
                ></line>
                <line
                  x1="0"
                  y1="800"
                  x2="100%"
                  y2="800"
                  strokeOpacity="0.2"
                ></line>
                <line
                  x1="0"
                  y1="810"
                  x2="100%"
                  y2="810"
                  strokeOpacity="0.19"
                ></line>
                <line
                  x1="0"
                  y1="820"
                  x2="100%"
                  y2="820"
                  strokeOpacity="0.18"
                ></line>
                <line
                  x1="0"
                  y1="830"
                  x2="100%"
                  y2="830"
                  strokeOpacity="0.17"
                ></line>
                <line
                  x1="0"
                  y1="840"
                  x2="100%"
                  y2="840"
                  strokeOpacity="0.16"
                ></line>
                <line
                  x1="0"
                  y1="850"
                  x2="100%"
                  y2="850"
                  strokeOpacity="0.15"
                ></line>
                <line
                  x1="0"
                  y1="860"
                  x2="100%"
                  y2="860"
                  strokeOpacity="0.14"
                ></line>
                <line
                  x1="0"
                  y1="870"
                  x2="100%"
                  y2="870"
                  strokeOpacity="0.13"
                ></line>
                <line
                  x1="0"
                  y1="880"
                  x2="100%"
                  y2="880"
                  strokeOpacity="0.12"
                ></line>
                <line
                  x1="0"
                  y1="890"
                  x2="100%"
                  y2="890"
                  strokeOpacity="0.11"
                ></line>
                <line
                  x1="0"
                  y1="900"
                  x2="100%"
                  y2="900"
                  strokeOpacity="0.1"
                ></line>
                <line
                  x1="0"
                  y1="910"
                  x2="100%"
                  y2="910"
                  strokeOpacity="0.09"
                ></line>
                <line
                  x1="0"
                  y1="920"
                  x2="100%"
                  y2="920"
                  strokeOpacity="0.08"
                ></line>
                <line
                  x1="0"
                  y1="930"
                  x2="100%"
                  y2="930"
                  strokeOpacity="0.07"
                ></line>
                <line
                  x1="0"
                  y1="940"
                  x2="100%"
                  y2="940"
                  strokeOpacity="0.06"
                ></line>
                <line
                  x1="0"
                  y1="950"
                  x2="100%"
                  y2="950"
                  strokeOpacity="0.05"
                ></line>
                <line
                  x1="0"
                  y1="960"
                  x2="100%"
                  y2="960"
                  strokeOpacity="0.04"
                ></line>
                <line
                  x1="0"
                  y1="970"
                  x2="100%"
                  y2="970"
                  strokeOpacity="0.03"
                ></line>
                <line
                  x1="0"
                  y1="980"
                  x2="100%"
                  y2="980"
                  strokeOpacity="0.02"
                ></line>
                <line
                  x1="0"
                  y1="990"
                  x2="100%"
                  y2="990"
                  strokeOpacity="0.01"
                ></line>
              </pattern>
            </defs>
            <rect
              width="100%"
              height="100%"
              strokeWidth="0"
              fill="url(#_S_f_)"
            ></rect>
          </svg>
          <svg
            width="1152"
            height="258"
            viewBox="0 0 824 258"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="opacity-100"
          >
            <text
              x="50%"
              y="50%"
              dominantBaseline="middle"
              textAnchor="middle"
              className="fill-slate-950/[0.1] stroke-slate-950/[0.05] dark:fill-zinc-800 dark:stroke-neutral-700 font-bold tracking-tight"
              style={{
                fontSize: "196px",
                strokeWidth: 1.2,
                paintOrder: "stroke",
              }}
            >
              Admin12121
            </text>
          </svg>
        </div>
      </div>
    </>
  );
};

export default Footer;

function Separator() {
  return <div className="flex h-11 w-px bg-edge" />;
}
